<?php

namespace MusicFestival;

require_once dirname(__FILE__) . '/../../../lib/MusicFestival/Person.php';

/**
 * Test class for Person.
 * Generated by PHPUnit on 2012-06-10 at 10:54:48.
 */
class PersonTest extends \PHPUnit_Framework_TestCase {

  /**
   * @test
   */
  function fromArrayConstructionTest()
  {
    $person = Person::fromArray(array(
      'name' => 'Robert Onion',
    ));

    $this->assertEquals('Robert Onion', $person->getName());
  }

}
