<?php

namespace MusicFestival;

require_once dirname(__FILE__) . '/../../../lib/MusicFestival/Track.php';

/**
 * Test class for Track.
 * Generated by PHPUnit on 2012-06-10 at 22:08:16.
 */
class TrackTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Track
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Track;
  }

  /**
   * @covers MusicFestival\Track::getTitle
   */
  public function testGetTitle() {
    $this->assertNull($this->object->getTitle());
    $this->object->setAttribute(Track::ATTR_TITLE, 'niek');
    $this->assertEquals('niek', $this->object->getTitle());
  }

  /**
   * @covers MusicFestival\Track::getMemo
   */
  public function testGetMemo() {
    $this->assertNull($this->object->getTitle());
    $this->object->setAttribute(Track::ATTR_MEMO, 'niek');
    $this->assertEquals('niek', $this->object->getMemo());
  }

  /**
   * @covers MusicFestival\Track::getArtist
   */
  public function testGetArtist() {
    $this->assertNull($this->object->getArtist());
    $this->object->setAttribute(Track::ATTR_ARTIST, 'niek');
    $this->assertEquals('niek', $this->object->getArtist());
  }

  /**
   * @covers MusicFestival\Track::getAlbum
   */
  public function testGetAlbum() {
    $this->assertNull($this->object->getAlbum());
    $this->object->setAttribute(Track::ATTR_ALBUM, 'niek');
    $this->assertEquals('niek', $this->object->getAlbum());
  }

  /**
   * @covers MusicFestival\Track::getYear
   */
  public function testGetYear() {
    $this->assertNull($this->object->getYear());
    $this->object->setAttribute(Track::ATTR_YEAR, 'niek');
    $this->assertEquals('niek', $this->object->getYear());
  }

  /**
   * @covers MusicFestival\Track::getCover
   */
  public function testGetCover() {
    $this->assertNull($this->object->getCover());
    $this->object->setAttribute(Track::ATTR_COVER, 'niek');
    $this->assertEquals('niek', $this->object->getCover());
  }

  /**
   * @covers MusicFestival\Track::getLinks
   * @todo Implement testGetLinks().
   */
  public function testGetLinks() {
    $this->assertInternalType('array', $this->object->getLinks());
    $this->assertCount(0, $this->object->getLinks());

    $this->object->setLinks(array('niiek','nieek'));

    $this->assertEquals(array('niiek','nieek'), $this->object->getLinks());
  }

  /**
   * @covers MusicFestival\Track::fromArray
   */
  public function testFromArray() {
    $track = Track::fromArray(array(
      'title' => 'Titre de la chanson',
    ));

    $this->assertEquals('Titre de la chanson', $track->getTitle());
    $this->assertEquals('Titre de la chanson', $track->getAttribute(Track::ATTR_TITLE));
  }
}