<?php

namespace MusicFestival\Link;

require_once dirname(__FILE__) . '/../../../../lib/MusicFestival/Link/Factory.php';

/**
 * Test class for Factory.
 * Generated by PHPUnit on 2012-06-13 at 01:16:11.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase {

  public function testGetDefaultClasses() {
    $classes = \MusicFestival\Link\Factory::getDefaultClasses();
    $this->assertInternalType('array', $classes);
    foreach($classes as $class) {
      $this->assertContains('MusicFestival\Link\Link', class_implements($class));
    }
  }

  /**
   * @covers MusicFestival\Link\Factory::fromUrl
   * @todo Implement testFromUrl().
   */
  public function testFromUrl() {
    $linkClass = $this->getMockClass('Link');

    $linkClass::staticExpects($this->any())
          ->method('isMatchingUrl')
          ->will($this->returnValue(false));

    $this->assertInstanceOf('MusicFestival\Link\DefaultLink', \MusicFestival\Link\Factory::fromUrl('http://bullcrap.com/'));
  }

}