#
# Configuration for Music-Festival app
# More about YAML: http://symfony.com/doc/current/components/yaml.html#the-yaml-format
#

#
# Your screen name
name: Robert Onion

#
# Your tracks
tracks:

  #
  # Full - Example with all fields set
  #
  1:
    title:  La Javanaise
    artist: Serge Gainsbourg
    album:  Intégrale
    cover:  http://userserve-ak.last.fm/serve/174s/33029863.jpg
    # MusicBrainz Recording ID - Useful to distinct two homonym tracks
    # Or for lazy people to automatically set everything else
    # The MusicBrainz ID MUST exist at LastFm to be useful
    # Search your track : http://musicbrainz.org/search
    mbid:   938bd84a-24a8-417d-a1eb-da33d5dbeca1
    # Some fluf to be added to the song
    # Note that you can split lines.
    memo: >
      Certainement ma chanson préférée de <b>Gainsbourg</b> avec
      <a href="http://linkto.com/niekniek/">Overseas telegram</a>.
      Mais j'aime aussi <b>mettre du gras</b> et d'autres <em>
      balises html</em>
    # Tags are a simple set of key (tag label) and url (tag location)
    tags:
      metalcore:  http://www.lastfm.fr/tag/metalcore
      french:     http://www.lastfm.fr/tag/french
    # Links are quite open. You can add any kind of http:// link
    # Some services such as Youtube, Spotify, Deezer, Soundcloud, GrooveShark, …
    # are automatically loaded
    links:
      - http://www.youtube.com/watch?v=3kicpfXUOXc
      - http://www.dailymotion.com/video/x22c2v_gainsbourg-serge-la-javanaise_music
      - http://soundcloud.com/humanoide/javanaise
      - http://grooveshark.com/s/La+Javanaise/3UYWXK?src=5

  2:
    # Lazy example, only Title and Artist.
    # MusicFestival will ask LastFm for you.
    title:  L'Aventurier
    artist: Indochine
    memo:   Bob morane contre doux chacal l'aventurier contre douze guerriers!

  3:
    # Lazy (but precise) example, only MBID
    # MusicFestival will ask LastFm for you.
    mbid:   028523f5-23b3-4910-adc1-46d932e2fb55

  4:
    title:  Pas de cover
    artist: Lady Gaga
    album:  The Fame
    mbid:   f53304ee-dbdf-4af9-9f97-58dd5c24e864I
    memo:   J'aime lady gaga ! Et toc.
    links:
      - http://open.spotify.com/track/3nE7aH8voaa5O2IFWkcf7i

  5:
    title:  Bullcrap
    artist: Lady Bulltrap
    album:  The Bullcrap
    mbid:   bullcrap
    memo:   Check lastfm bulletproofness
    links:
      - http://open.spotify.com/track/3nE7aH8voaa5O2IFWkcf7i