name: Robert Onion
id:   12347

tracks:
  1:
    title:  La Javanaise
    artist: Serge Gainsbourg
    album:  Intégrale
    mbid:   938bd84a-24a8-417d-a1eb-da33d5dbeca1
    memo:   Certainement ma chanson préférée de <b>Gainsbourg</b> avec <a href="http://www.lastfm.fr/music/Serge+Gainsbourg/_/Overseas+Telegram?ac=telegram+gain">Overseas telegram</a> .
    tags:
      test: value
    links:
      - http://www.youtube.com/watch?v=3kicpfXUOXc
      - http://www.dailymotion.com/video/x22c2v_gainsbourg-serge-la-javanaise_music
      - http://soundcloud.com/humanoide/javanaise
      - http://grooveshark.com/s/La+Javanaise/3UYWXK?src=5

  2:
    title:  L'Aventurier
    artist: Indochine
    album:  L'Aventurier
    mbid:   02804644-68e5-4299-a5de-58d514c0f3db
    memo:   Bob morane contre doux chacal l'aventurier contre douze guerriers!

  3:
    title:  Pas de cover
    artist: Lady Gaga
    album:  The Fame
    mbid:   f53304ee-dbdf-4af9-9f97-58dd5c24e864
    memo:   J'aime lady gaga ! Et toc.

  4:
    mbid:   028523f5-23b3-4910-adc1-46d932e2fb55

  5:
    title:  Bullcrap
    artist: Lady Bulltrap
    album:  The Bullcrap
    mbid:   bullcrap
    memo:   Check lastfm bulletproofness
    links:
      - http://open.spotify.com/track/3nE7aH8voaa5O2IFWkcf7i